### ISSUE TITLE
FROM and TO Wrong Way Around

### ISSUE THREAD

**Issue by owen-h-bellis** [hatlord/paloparser#1]
The following code snippet will need adjusting.
The FROM is matching TO instead of FROM, and vice versa.

      rules[:**from**interface] = rule.xpath('./to/member').map(&:text).join("\r")
      rules[:tointerface]   = rule.xpath('./**from**/member').map(&:text).join("\r")

**Comment by owen-h-bellis** [comment]
Currently only supports VSYS and not DEVICE-GROUP.
Recommend adding the following:
      entry.xpath('./pre-rulebase/security/rules/entry').each do |rule|
      entry.xpath('./post-rulebase/security/rules/entry').each do |rule|
      entry.xpath('./pre-rulebase/decryption/rules/entry').each do |rule|
      entry.xpath('./post-rulebase/decryption/rules/entry').each do |rule|

**Comment by hatlord** [comment]
Fixed in https://github.com/hatlord/paloparser/commit/25dcee067243090155ebb6ead569e5ed11d805ce
