### ISSUE TITLE
Support for DEVICE-GROUP

### ISSUE THREAD

**Issue by owen-h-bellis** [hatlord/paloparser#2]
Currently only supports VSYS and not DEVICE-GROUP.
Recommend adding the following:
entry.xpath('./pre-rulebase/security/rules/entry').each do |rule|
entry.xpath('./post-rulebase/security/rules/entry').each do |rule|
entry.xpath('./pre-rulebase/decryption/rules/entry').each do |rule|
entry.xpath('./post-rulebase/decryption/rules/entry').each do |rule|

**Comment by hatlord** [comment]
Excel file is now written with a sheet for each of the above. If rules aren't present, the sheet will be empty.

https://github.com/hatlord/paloparser/commit/39f37950081aaa6590a23664d73d4f91b4eabb7f
